### PR TITLE
Drop prerelease flag in go releaser

### LINKED ISSUE #357: Do not mark releases as `pre-release`
See #352

### PR DESCRIPTION
**Pull request by gabo1208**
Fixes #357

### CODE REVIEW

**Comment by embano1** [comment]
IMHO you need to update the RELEASE instructions too

**Review by embano1 — DISMISSED** [review]
LGTM.

nit: you have one commit in there which is not needed, not sure if that's intentional

**Comment by embano1** [comment]
Hm, looks like you dropped the wrong commit?

**Comment by gabo1208** [comment]
You are right XD made the wrong commit to start with, now it should be ready

**Review by embano1 — APPROVED** [review]
LGTM

Still wonder why https://github.com/vmware-tanzu/sources-for-knative/pull/368/commits/42f6514d96da6b4af046452417758cb8b37a3cd7 is in here

**Comment by gabo1208** [comment]
I think my fork got out of sync let me fix this

**Pull request merged**
