### PR TITLE
bump to v0.15.0

### PR DESCRIPTION
**Pull request by vaikas**

### CODE REVIEW

**Review by n3wscott — DISMISSED** [review]
Why is the verify failing?

**Comment by vaikas** [comment]
```
1m 24s
##[error]Process completed with exit code 2.
Run go get github.com/golang/dep/cmd/dep
# github.com/google/go-licenses
##[error]src/github.com/google/go-licenses/save.go:121:22: cannot use func literal (type func(string) bool) as type func(string) (bool, error) in field value
##[error]Process completed with exit code 2.
```

**Comment by n3wscott** [comment]
might be an old test infra

**Comment by vaikas** [comment]
https://github.com/google/go-licenses/issues/22

**Comment by otiai10** [comment]
will be solved by https://github.com/google/go-licenses/pull/23

**Review by n3wscott — APPROVED** [review]

**Pull request merged**
